import type { Metadata } from 'next';
import { Geist, Geist_Mono, Montserrat } from 'next/font/google';
import './globals.css';
import localFont from 'next/font/local';
import { auth } from '../../auth';
import { SessionProvider } from 'next-auth/react';
import { CartSheet } from '../modules/cart/components/CartLateral';

const goldplay = localFont({
	src: [
		{
			path: './fonts/GoldplayAlt-Regular.ttf',
			weight: '400',
			style: 'normal',
		},
		{
			path: './fonts/GoldplayAlt-Bold.ttf',
			weight: '700',
			style: 'normal',
		},
	],
});
const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const montserrat = Montserrat({
	variable: '--font-montserrat',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const session = await auth();

	return (
		<SessionProvider session={session}>
			<html lang="es" suppressHydrationWarning>
				<body
					className={`${montserrat.variable}  ${geistSans.variable} ${goldplay.className} ${geistMono.variable}  !font-montserrat-fuente min-h-screen antialiased`}
				>
					{/* contenido del carrito */}
					<CartSheet />
					{children}
				</body>
			</html>
		</SessionProvider>
	);
}
